#version: '2'

services:
  app:
    image: 'spring-boot-docker'
    build:
      context: .
    container_name: app
    depends_on:
      - mysql
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/employee_directory
      - SPRING_DATASOURCE_USERNAME=springstudent
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    environment:
      - MYSQL_DATABASE=employee_directory
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
